export type RootStackParamList = {
  Home: undefined;
  Landing: undefined;
  MainPage: undefined;
  DetailPage: undefined;
  NungilList: undefined;
  Login: undefined;
  KakaoLoginRedirect: undefined;
  QnA: undefined;
  DetailProfile: undefined;
  AnswerPage: undefined;
  Register: {stepIndex: number};
  IdealType: undefined;
  QuestionList: undefined;
  Chat: undefined;
  ChatRoom: {chatRoomId: number};
  MyPage: undefined;
  BottomNavLayout: undefined;
  EditProfile: undefined;
};
